eTrainingSolution.WebApp/Areas/Identity/Controllers/FacultController.cs
using eTrainingSolution.EntityFrameworkCore;
using eTrainingSolution.EntityFrameworkCore.Entities;
using eTrainingSolution.Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace eTrainingSolution.WebApp.Areas.Identity.Controllers
{
    [Area("Identity")]
    [Route("/Facult/[action]")]
    public class FacultController : PublicController
    {
        #region Khai báo dbContext sử dụng
        public FacultController(SignInManager<UserInfo> signInManager, UserManager<UserInfo> userManager, DB_Context context, RoleManager<IdentityRole> roleManager)
            : base(signInManager, userManager, context, roleManager)
        {
        }
        #endregion

        #region Index
        [Authorize(Roles = RoleType.Admin_Manage)]
        [HttpGet]
        public async Task<IActionResult> Index(string search)
        {
            if (!string.IsNullOrEmpty(search))
            {
                var facultSearch = from facult in _context.FacultET select facult;
                facultSearch = facultSearch.Where(x => x.Schools.Name.Contains(search));
                return View(await facultSearch.Include(f => f.Schools).OrderBy(m => m.Name).ToListAsync());
            }
            bool isAdmin = await IsAdmin();
            if (!isAdmin)
            {
                UserInfo user = await getUserET();
                var facultDB = _context.FacultET.Include(f => f.Schools).Where(m => m.SchoolID == user.SchoolID).OrderBy(m => m.Name);
                return View(await facultDB.ToListAsync());
            }
            ViewBag.isAdmin = "Admin";
            return View(await _context.FacultET.Include(f => f.Schools).OrderBy(m => m.Name).ToListAsync());
        }

        #endregion

        #region Tạo mới một Khoa

        [Authorize(Roles = RoleType.Admin_Manage)]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            bool isAdmin = await IsAdmin();
            if (!isAdmin)
            {
                UserInfo user = await getUserET();
                ViewData["SchoolID"] = new SelectList(_context.SchoolET.Where(m => m.ID == user.SchoolID), Default.ID, Default.SchoolName);
                return View();
            }
            ViewBag.isAdmin = "Admin";
            ViewData["SchoolID"] = new SelectList(_context.SchoolET, Default.ID, Default.SchoolName);
            return View();
        }

        [HttpPost]
        [Authorize(Roles = RoleType.Admin_Manage)]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Create([Bind(Default.BindFacult)] Facult facult)
        {
            if (ModelState.IsValid)
            {
                facult.ID = Guid.NewGuid();
                _context.Add(facult);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SchoolID"] = new SelectList(_context.SchoolET, Default.ID, Default.SchoolName, facult.SchoolID);
            return View(facult);
        }

        #endregion

        #region Sửa thông tin Khoa

        [Authorize(Roles = RoleType.Admin_Manage)]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (string.IsNullOrEmpty(id.ToString()))
            {
                return NotFound(Default.NotificationFacult);
            }
            /* Lấy thông tin Khoa theo ID */
            var facultDB = await _context.FacultET.FindAsync(id);

            bool isAdmin = await IsAdmin();
            if (!isAdmin)
            {
                UserInfo user = await getUserET();
                ViewData["SchoolID"] = new SelectList(_context.SchoolET.Where(m => m.ID == user.SchoolID), Default.ID, Default.SchoolName, facultDB.SchoolID);
                return View(facultDB);
            }
            ViewData["SchoolID"] = new SelectList(_context.SchoolET.Where(m => m.ID == facultDB.SchoolID), Default.ID, Default.SchoolName, facultDB.SchoolID);
            return View(facultDB);
        }

        [HttpPost]
        [Authorize(Roles = RoleType.Admin_Manage)]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(Guid? id, [Bind(Default.BindFacult)] Facult facult)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var facultDb = _context.FacultET.Find(id);
                    _context.Entry(facultDb).CurrentValues.SetValues(facult);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SchoolID"] = new SelectList(_context.SchoolET, Default.ID, Default.SchoolName, facult.SchoolID);
            return View(facult);
        }

        #endregion

        #region Xóa thông tin của Khoa

        [HttpGet]
        [Authorize(Roles = RoleType.Admin_Manage)]
        public async Task<IActionResult> Delete(Guid? id) => await View(id);

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = RoleType.Admin_Manage)]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid? id)
        {
            if (!string.IsNullOrEmpty(id.ToString()))
            {
                /* Lấy danh sách user thuộc Khoa */
                var lstUser = await _context.UserET?.Where(m => m.FacultID == id).ToListAsync();
                if(lstUser.Count > 0)
                {
                     _context.RemoveRange(lstUser);
                }
                /* Lấy danh sách lớp thuộc trường */
                var lstClass = await _context.ClassET.Where(m => m.FacultID == id).ToListAsync();
                if (lstClass.Count > 0)
                {
                    _context.RemoveRange(lstClass);
                }
                /* lấy Khoa muốn xóa */
                var facultDB = await _context.FacultET.FindAsync(id);

                _context.FacultET.Remove(facultDB);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            return NotFound(Default.NotificationFacult);
        }

        #endregion

        #region Xem thông tin của Khoa

        [HttpGet]
        [Authorize(Roles = RoleType.Admin_Manage)]
        public async Task<IActionResult> View(Guid? id)
        {
            if (!string.IsNullOrEmpty(id.ToString()))
            {
                var facultDB = await _context.FacultET.Include(g => g.Schools).FirstOrDefaultAsync(m => m.ID == id);
                return View(facultDB);
            }
            return NotFound(Default.NotificationFacult);
        }

        #endregion
    }
}

eTrainingSolution.WebApp/Areas/Identity/Controllers/RoleController.cs
using eTrainingSolution.EntityFrameworkCore;
using eTrainingSolution.EntityFrameworkCore.Entities;
using eTrainingSolution.Shared;
using eTrainingSolution.WebApp.Areas.Identity.Models.Role;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTrainingSolution.WebApp.Areas.Identity.Controllers
{
    [Area("Identity")]
    [Route("/Role/[action]")]
    public class RoleController : PublicController
    {
        #region Khai báo các dịch vụ sử dụng
        public RoleController(SignInManager<UserInfo> signInManager, UserManager<UserInfo> userManager, DB_Context context, RoleManager<IdentityRole> roleManager)
            : base(signInManager, userManager, context, roleManager)
        {
        }
        #endregion

        #region index

        /// <summary>
        /// HTTPGet đến trang quản lý Role
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Authorize(Roles = RoleType.Admin)]
        public async Task<IActionResult> Index()
        {
            var data = await _roleManager.Roles.OrderBy(data => data.Name).ToListAsync();
            return View(data);
        }

        #endregion

        #region Tạo role mới

        /// <summary>
        /// Url /Role/Create
        /// </summary>
        /// <returns>giao diện tạo role mới</returns>
        [HttpGet]
        [Authorize(Roles = RoleType.Admin)]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = RoleType.Admin)]
        [HttpPost, ActionName("Create")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> CreateAsync(RoleModel model)
        {
            if (ModelState.IsValid)
            {
                var newRole = new IdentityRole(model.Name);
                var result = await _roleManager.CreateAsync(newRole);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View();
        }

        #endregion

        #region Xóa role

        [Authorize(Roles = RoleType.Admin)]
        [HttpGet("{roleID}")]
        public async Task<IActionResult> DeleteAsync(string roleID)
        {
            if (roleID == null)
            {
                return NotFound(Default.NotificationRole);
            }
            var role = await _roleManager.FindByIdAsync(roleID);
            return View(role);
        }


        [Authorize(Roles = RoleType.Admin)]
        [AutoValidateAntiforgeryToken]
        [HttpPost("{roleID}"), ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmAsync(string roleID)
        {
            if (roleID == null)
            {
                return NotFound(Default.NotificationRole);
            }
            var role = await _roleManager.FindByIdAsync(roleID);

            var result = await _roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                return RedirectToAction(nameof(Index));
            }
            ModelState.AddModelError(string.Empty, "Không xóa được role");
            return View(role);
        }
        #endregion

        #region Sửa role

        /// <summary>
        /// 
        /// </summary>
        /// <param name="roleID">id role được truyền vào từ object ở trang trước đó</param>
        /// <param name="model">model</param>
        /// <returns></returns>
        [HttpGet("{roleID}")]
        [Authorize(Roles = RoleType.Admin)]
        public async Task<IActionResult> EditAsync(string roleID, [Bind("Name")] RoleModel model)
        {
            if (roleID == null)
            {
                return NotFound(Default.NotificationRole);
            }
            // tìm kiếm role
            var role = await _roleManager.FindByIdAsync(roleID);
            if (role.Name == RoleType.Admin)
            {
                return RedirectToAction(nameof(Index));
            }
            model.Name = role.Name;
            ModelState.Clear();
            return View(model);
        }

        [AutoValidateAntiforgeryToken]
        [Authorize(Roles = RoleType.Admin)]
        [HttpPost("{roleID}"), ActionName("Edit")]
        public async Task<IActionResult> EditConfirmAsync(string roleID, [Bind("Name")] RoleModel model)
        {
            if (roleID == null)
            {
                return NotFound(Default.NotificationRole);
            }
            var role = await _roleManager.FindByIdAsync(roleID);
            role.Name = model.Name;
            var result = await _roleManager.UpdateAsync(role);
            if (result.Succeeded)
            {
                return RedirectToAction(nameof(Index));
            }
            ModelState.AddModelError(string.Empty, "Không sửa được role");
            return View(model);
        }

        #endregion
    }
}

eTrainingSolution.WebApp/Areas/Identity/Controllers/SchoolController.cs
using eTrainingSolution.EntityFrameworkCore;
using eTrainingSolution.EntityFrameworkCore.Entities;
using eTrainingSolution.Shared;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace eTrainingSolution.WebApp.Areas.Identity.Controllers
{
    [Area("Identity")]
    [Route("/School/[action]")]
    public class SchoolController : PublicController
    {
        #region Kế thừa BaseController
        public SchoolController(SignInManager<UserInfo> signInManager, UserManager<UserInfo> userManager, DB_Context context, RoleManager<IdentityRole> roleManager)
            : base(signInManager, userManager, context, roleManager)
        {
        }
        #endregion

        #region Index

        [HttpGet]
        [Authorize(Roles = RoleType.Admin_Manage)]
        public async Task<IActionResult> Index(string search)
        {
            if (!string.IsNullOrEmpty(search))
            {
                var schoolSearch = from school in _context.SchoolET select school;
                schoolSearch = schoolSearch.Where(x => x.Name.Contains(search));
                return View(await schoolSearch.OrderBy(m => m.Name).ToListAsync());
            }
            bool isAdmin = await IsAdmin();
            if (!isAdmin)
            {
                UserInfo user = await getUserET();
                var schoolDB = _context.SchoolET.Where(m => m.ID == user.SchoolID);
                return View(await schoolDB.ToListAsync());
            }
            ViewBag.isAdmin = "Admin";
            return View(await _context.SchoolET.OrderBy(m => m.Name).ToListAsync());
        }

        #endregion

        #region Create School

        [HttpGet]
        [Authorize(Roles = RoleType.Admin)]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = RoleType.Admin)]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Create([Bind(Default.BindSchool)] School school)
        {
            if (ModelState.IsValid)
            {
                school.ID = Guid.NewGuid();
                _context.Add(school);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(school);
        }

        #endregion

        #region Edit School

        [HttpGet]
        [Authorize(Roles = RoleType.Admin)]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (!string.IsNullOrEmpty(id.ToString()))
            {
                var schoolDB = await _context.SchoolET.FindAsync(id);
                return View(schoolDB);
            }
            return NotFound(Default.NotificationSchool);
        }

        [HttpPost]
        [Authorize(Roles = RoleType.Admin)]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind(Default.BindSchool)] School school)
        {
            if (id == school.ID)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(school);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        throw;
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(school);
            }
            return NotFound("Không thể sửa thông tin trường học");
        }

        #endregion

        #region Delete School

        [HttpGet]
        [Authorize(Roles = RoleType.Admin)]
        public Task<IActionResult> Delete(Guid? id) => Edit(id);

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = RoleType.Admin)]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid? id)
        {
            if (id == null) 
            {
                return NotFound();
            }
            /* Lấy danh sách User thuộc trường đó */
            var lstUser = await _context.UserET.Where(m => m.SchoolID == id).ToListAsync();
            if(lstUser.Count > 0)
            {
                _context.RemoveRange(lstUser);
            }

            /* Lấy danh sách lớp thuộc trường đó */
            var lstClass = await _context.ClassET.Where(m => m.SchoolID == id).ToListAsync();
            if (lstClass.Count > 0)
            {
                _context.RemoveRange(lstClass);
            }

            /* Lấy danh sách Khoa thuộc trường đó */
            var lstFacult = await _context.FacultET.Where(m => m.SchoolID == id).ToListAsync();
            if (lstFacult.Count > 0)
            {
                _context.RemoveRange(lstFacult);
            }

            // tìm kiếm thông tin trường học theo id
            var schoolDB = await _context.SchoolET.FindAsync(id);
            _context.Remove(schoolDB);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region View thông tin

        [HttpGet]
        [Authorize(Roles = RoleType.Admin + "," + RoleType.Manage)]
        public Task<IActionResult> View(Guid? id) => Edit(id);
        #endregion
    }
}

eTrainingSolution.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTrainingSolution.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/eTrainingSolution.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Quản lý trường học</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                @*        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        @*thêm vào menu các mục cần thiết cho bài toán*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-controller="School" asp-action="Index">Trường học</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="Identity" asp-controller="Facult" asp-action="Index">Khoa</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="Identity" asp-controller="Classes" asp-action="Index">Lớp học</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="Identity" asp-controller="Role" asp-action="Index">Vai trò</a>
                        </li>
                    </ul>
                    <partial name="_loginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - eTrainingSolution.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

eTrainingSolution.WebApp/Views/Shared/_PagingXTL.cshtml
@using eTrainingSolution.WebApp.Areas.Identity.Models.Page;

@model PagingModel

@{
    int currentPage = Model.currentPage;
    int countPage = Model.CountPage;
    var generateURL = Model.GenerateUrl;

    // Nếu mà trang hiện tại > tổng số trang thì gán cho là trang cuối cùng
    if (currentPage > countPage) currentPage = countPage;

    // Nếu mà không tồn tại trang nào thì return
    if (countPage <= 1) return;

    // khai báo 2 biến trang trước đó và trang tiếp theo
    int? preview = null;
    int? next = null;

    // Nếu trang hiện tại không phải là trang thứ nhất thì trang khi ấn preview sẽ quay lại trang trước đó
    if(currentPage > 1)
    {
        preview = currentPage - 1;
    }

    if(currentPage < countPage)
    {
        next = currentPage + 1;
    }

    // số trang mở rộng về mỗi bên cho trang hiện tại
    int delta = 5;
    // số trang hai bên trang hiện tại
    int remain = delta * 2;

    // Khai báo list các trang hiển thị để điều hướng
    List<int> pageRanges = new List<int>();

    pageRanges.Add(currentPage);

    // các trang phát triển về hai bên trang hiện tại
    for(int i = 1; i <= delta; i++)
    {
        if(currentPage + i <= countPage)
        {
            pageRanges.Add(currentPage + i);
            remain--;
        }
        if(currentPage - i >= 1)
        {
            pageRanges.Insert(0, currentPage - i);
            remain--;
        }
    }

    // xử lý thêm vào các trang cho đủ remain
    if(remain > 0)
    {
        if(pageRanges[0] == 1)
        {
            for(int i = 1; i <= remain; i++)
            {
                if(pageRanges.Last() + 1 <= countPage)
                {
                    pageRanges.Add(pageRanges.Last() + 1);
                }
            }
        }
        else
        {
            for(int i = 1; i <=remain; i++)
            {
                if(pageRanges.First() -1 > 1)
                {
                    pageRanges.Insert(0, pageRanges.First() - 1);
                }
            }
        }
    }
}

<ul class="pagination">
    @{
        if (preview != null)
        {
           <li class="page-item">
                <a class="page-link" href="@generateURL(preview)">Trang trước</a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang trước</a>
            </li>
        }

        @foreach(var pageItem in pageRanges)
        {
            if(pageItem != currentPage)
            {
                <li class="page-item">
                    <a class="page-link" href="@generateURL(pageItem)">@pageItem</a>
                </li>
            }
            else
            {
                <li class="page-item active" aria-current ="page">
                    <a class="page-link" href="#">@pageItem</a>
                </li>
            }
        }

        if (next != null)
        {
            <li class="page-item">
                <a class="page-link" href="@generateURL(next)">Trang sau</a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang sau</a>
            </li>
        }
    }
</ul>